#!/usr/bin/env python
"""Pack a directory of override files into one submittable submission.py.

Usage:
    python tools/pack_submission.py --overrides-dir path/to/my_changes --out submission.py

`overrides_dir` may contain any subset of model.py / schedule.py / data.py (and any
further files those import, since referee.py materializes the whole EXTRA_FILES map into
one scratch directory before importing -- see referee/referee.py). Everything in the
directory is packed; there is no allowlist here because the referee's own AST screen
(referee/screen.py) is what actually enforces safety, on the receiving end.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

TEMPLATE = '''"""Generated by tools/pack_submission.py from {source_dir!r}. Do not hand-edit --
edit the source files and re-run the packer instead."""

from __future__ import annotations

EXTRA_FILES: dict[str, str] = {extra_files_literal}
'''


def pack(overrides_dir: Path) -> str:
    extra_files = {
        str(path.relative_to(overrides_dir)): path.read_text()
        for path in sorted(overrides_dir.rglob("*.py"))
    }
    if not extra_files:
        raise ValueError(f"no .py files found in {overrides_dir}")
    return TEMPLATE.format(source_dir=str(overrides_dir), extra_files_literal=json.dumps(extra_files, indent=2))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--overrides-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path("submission.py"))
    args = parser.parse_args()
    args.out.write_text(pack(args.overrides_dir))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
